repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.11
        exclude: ^test/snapshots/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
