services:
  api:
    build: .
    ports:
      - "8001:8001"
    develop:
      watch:
        - action: rebuild
          path: .
          target: /home/myuser/code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001
    profiles:
      - prod
  api-dev:
    build: .
    ports:
      - "8001:8001"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /home/myuser/code/src
        - action: rebuild
          path: ./requirements.txt
          target: /home/myuser/code/requirements.txt
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload-exclude ./temp/** --reload
    profiles:
      - dev

networks:
  default:
    name: api-services
